import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CityService {

  constructor() { }

  getCities() {
    return [{ city: 'Sucre' },
    { city: 'Yotala' },
    { city: 'Poroma' },
    { city: 'Azurduy' },
    { city: 'Tarvita' },
    { city: 'Zudáñez' },
    { city: 'Presto' },
    { city: 'Mojocoya' },
    { city: 'Icla' },
    { city: 'Padilla' },
    { city: 'Tomina' },
    { city: 'Sopachuy' },
    { city: 'Villa Alcalá' },
    { city: 'El Villar' },
    { city: 'Monteagudo' },
    { city: 'Huacareta' },
    { city: 'Tarabuco' },
    { city: 'Yamparáez' },
    { city: 'Camargo' },
    { city: 'San Lucas' },
    { city: 'Incahuasi' },
    { city: 'Villa Charcas' },
    { city: 'Villa Serrano' },
    { city: 'Villa Abecia' },
    { city: 'Culpina' },
    { city: 'Las Carreras' },
    { city: 'Muyupampa' },
    { city: 'Huacaya' },
    { city: 'Macharetí' },
    { city: 'La Paz' },
    { city: 'Palca' },
    { city: 'Mecapaca' },
    { city: 'Achocalla' },
    { city: 'El Alto' },
    { city: 'Achacachi' },
    { city: 'Ancoraimes' },
    { city: 'Chua Cocani' },
    { city: 'Huarina' },
    { city: 'Santiago de Huata' },
    { city: 'Huatajata' },
    { city: 'Corocoro' },
    { city: 'Caquiaviri' },
    { city: 'Calacoto' },
    { city: 'Comanche' },
    { city: 'Charaña' },
    { city: 'Waldo Ballivián' },
    { city: 'Nazacara de Pacajes' },
    { city: 'Callapa' },
    { city: 'Puerto Acosta' },
    { city: 'Mocomoco' },
    { city: 'Pto. Carabuco' },
    { city: 'Humanata' },
    { city: 'Escoma' },
    { city: 'Chuma' },
    { city: 'Ayata' },
    { city: 'Aucapata' },
    { city: 'Sorata' },
    { city: 'Guanay' },
    { city: 'Tacacoma' },
    { city: 'Quiabaya' },
    { city: 'Combaya' },
    { city: 'Tipuani' },
    { city: 'Mapiri' },
    { city: 'Teoponte' },
    { city: 'Apolo' },
    { city: 'Pelechuco' },
    { city: 'Viacha' },
    { city: 'Guaqui' },
    { city: 'Tiahuanacu' },
    { city: 'Desaguadero' },
    { city: 'San Andrés de Machaca' },
    { city: 'Jesús de Machaca' },
    { city: 'Taraco' },
    { city: 'Luribay' },
    { city: 'Sapahaqui' },
    { city: 'Yaco' },
    { city: 'Malla' },
    { city: 'Cairoma' },
    { city: 'Inquisivi' },
    { city: 'Quime' },
    { city: 'Cajuata' },
    { city: 'Colquiri' },
    { city: 'Ichoca' },
    { city: 'Villa Libertad Licoma' },
    { city: 'Chulumani' },
    { city: 'Irupana' },
    { city: 'Yanacachi' },
    { city: 'Palos Blancos' },
    { city: 'La Asunta' },
    { city: 'Pucarani' },
    { city: 'Laja' },
    { city: 'Batallas' },
    { city: 'Puerto Pérez' },
    { city: 'Sica Sica' },
    { city: 'Umala' },
    { city: 'Ayo Ayo' },
    { city: 'Calamarca' },
    { city: 'Patacamaya' },
    { city: 'Colquencha' },
    { city: 'Collana' },
    { city: 'Coroico' },
    { city: 'Coripata' },
    { city: 'Ixiamas' },
    { city: 'San Buenaventura' },
    { city: 'Charazani' },
    { city: 'Curva' },
    { city: 'Copacabana' },
    { city: 'San Pedro de Tiquina' },
    { city: 'Tito Yupanqui' },
    { city: 'San Pedro Cuarahuara' },
    { city: 'Papel Pampa' },
    { city: 'Chacarilla' },
    { city: 'Santiago de Machaca' },
    { city: 'Catacora' },
    { city: 'Caranavi' },
    { city: 'Alto Beni' },
    { city: 'Cochabamba' },
    { city: 'Aiquile ' },
    { city: 'Pasorapa ' },
    { city: 'Omereque ' },
    { city: 'Independencia' },
    { city: 'Morochata ' },
    { city: 'Cocapata' },
    { city: 'Tarata ' },
    { city: 'Anzaldo ' },
    { city: 'Arbieto ' },
    { city: 'Sacabamba ' },
    { city: 'Arani ' },
    { city: 'Vacas ' },
    { city: 'Arque ' },
    { city: 'Tacopaya ' },
    { city: 'Capinota ' },
    { city: 'Santiváñez ' },
    { city: 'Sicaya ' },
    { city: 'Cliza ' },
    { city: 'Toco ' },
    { city: 'Tolata ' },
    { city: 'Quillacollo ' },
    { city: 'Sipesipe ' },
    { city: 'Tiquipaya ' },
    { city: 'Vinto ' },
    { city: 'Colcapirhua ' },
    { city: 'Sacaba ' },
    { city: 'Colomi ' },
    { city: 'Villa Tunari ' },
    { city: 'Tapacarí ' },
    { city: 'Totora ' },
    { city: 'Pojo ' },
    { city: 'Pocona ' },
    { city: 'Chimoré ' },
    { city: 'Puerto Villarroel ' },
    { city: 'Entre Ríos' },
    { city: 'Mizque ' },
    { city: 'Vila Vila ' },
    { city: 'Alalay ' },
    { city: 'Punata ' },
    { city: 'Villa Rivero ' },
    { city: 'San Benito ' },
    { city: 'Tacachi ' },
    { city: 'Cuchumuela ' },
    { city: 'Bolívar ' },
    { city: 'Tiraque ' },
    { city: 'Shinahota' },
    { city: 'Oruro' },
    { city: 'Caracollo' },
    { city: 'El Choro' },
    { city: 'Soracachi' },
    { city: 'Challapata' },
    { city: 'Quillacas' },
    { city: 'Corque' },
    { city: 'Choque Cota' },
    { city: 'Curahuara de Carangas' },
    { city: 'Turco' },
    { city: 'Huachacalla' },
    { city: 'Escara' },
    { city: 'Cruz de Machacamarca' },
    { city: 'Yunguyo de Litoral' },
    { city: 'Esmeralda' },
    { city: 'Poopó' },
    { city: 'Pazña' },
    { city: 'Antequera' },
    { city: 'Huanuni' },
    { city: 'Machacamarca' },
    { city: 'Salinas de García Mendoza' },
    { city: 'Pampa Aullagas' },
    { city: 'Sabaya' },
    { city: 'Coipasa' },
    { city: 'Chipaya' },
    { city: 'Toledo' },
    { city: 'Eucaliptus' },
    { city: 'Santiago de Andamarca' },
    { city: 'Belén de Andamarca' },
    { city: 'San Pedro de Totora' },
    { city: 'Huari' },
    { city: 'La Rivera' },
    { city: 'Todos Santos' },
    { city: 'Carangas' },
    { city: 'Huayllamarca' },
    { city: 'Potosí' },
    { city: 'Tinguipaya' },
    { city: 'Yocalla' },
    { city: 'Urmiri' },
    { city: 'Uncía' },
    { city: 'Chayanta - Pueblo' },
    { city: 'Llallagua' },
    { city: 'Chuquihuta Ayllu Jucumani' },
    { city: 'Betanzos' },
    { city: 'Chaquí' },
    { city: 'Tacobamba' },
    { city: 'Colquechaca' },
    { city: 'Ravelo' },
    { city: 'Pocoata' },
    { city: 'Ocurí' },
    { city: 'S.P. De Buena Vista' },
    { city: 'Toro Toro' },
    { city: 'Cotagaita' },
    { city: 'Vitichi' },
    { city: 'Villa de Sacaca' },
    { city: 'Caripuyo' },
    { city: 'Tupiza' },
    { city: 'Atocha' },
    { city: 'Colcha "K"' },
    { city: 'San Pedro de Quemes' },
    { city: 'San Pablo de Lipez' },
    { city: 'Mojinete' },
    { city: 'San Antonio de Esmoruco' },
    { city: 'Puna' },
    { city: 'Caiza "D"' },
    { city: 'Ckochas' },
    { city: 'Uyuni' },
    { city: 'Tomave' },
    { city: 'Porco' },
    { city: 'Arampampa' },
    { city: 'Acasio' },
    { city: 'Llica' },
    { city: 'Tahua' },
    { city: 'Villazón' },
    { city: 'San Agustín' },
    { city: 'Tarija' },
    { city: 'Padcaya' },
    { city: 'Bermejo' },
    { city: 'Yacuiba' },
    { city: 'Caraparí' },
    { city: 'Villamontes' },
    { city: 'Uriondo' },
    { city: 'Yunchará' },
    { city: 'Villa San Lorenzo' },
    { city: 'El Puente' },
    { city: 'Entre Ríos' },
    { city: 'Santa Cruz de la Sierra' },
    { city: 'Cotoca' },
    { city: 'Porongo' },
    { city: 'La Guardia' },
    { city: 'El Torno' },
    { city: 'Warnes' },
    { city: 'Okinawa Uno' },
    { city: 'San Ignacio de Velasco' },
    { city: 'San Miguel de Velasco' },
    { city: 'San Rafael' },
    { city: 'Buena Vista' },
    { city: 'San Carlos' },
    { city: 'Yapacaní' },
    { city: 'San Juan' },
    { city: 'San José de Chiquitos' },
    { city: 'Pailón' },
    { city: 'Roboré' },
    { city: 'Portachuelo' },
    { city: 'Santa Rosa del Sara' },
    { city: 'Colpa Belgica' },
    { city: 'Lagunillas' },
    { city: 'Charagua' },
    { city: 'Cabezas' },
    { city: 'Cuevo' },
    { city: 'Gutiérrez' },
    { city: 'Camiri' },
    { city: 'Boyuibe' },
    { city: 'Vallegrande' },
    { city: 'Trigal' },
    { city: 'Moro Moro' },
    { city: 'Postrer Valle' },
    { city: 'Pucara' },
    { city: 'Samaipata' },
    { city: 'Pampa Grande' },
    { city: 'Mairana' },
    { city: 'Quirusillas' },
    { city: 'Montero' },
    { city: 'Gral. Saavedra' },
    { city: 'Mineros' },
    { city: 'Fernández Alonso' },
    { city: 'San Pedro' },
    { city: 'Concepción' },
    { city: 'San Javier' },
    { city: 'San Ramón' },
    { city: 'San Julián' },
    { city: 'San Antonio de Lomerío' },
    { city: 'Cuatro Cañadas' },
    { city: 'San Matías' },
    { city: 'Comarapa' },
    { city: 'Saipina' },
    { city: 'Puerto Suarez' },
    { city: 'Puerto Quijarro' },
    { city: 'Carmen Rivero Torrez' },
    { city: 'Ascensión de Guarayos' },
    { city: 'Urubichá' },
    { city: 'El Puente' },
    { city: 'Trinidad ' },
    { city: 'San Javier ' },
    { city: 'Riberalta ' },
    { city: 'Guayaramerín ' },
    { city: 'Reyes ' },
    { city: 'San Borja ' },
    { city: 'Santa Rosa ' },
    { city: 'Rurrenabaque ' },
    { city: 'Santa Ana del Yacuma ' },
    { city: 'Exaltación ' },
    { city: 'San Ignacio ' },
    { city: 'Loreto' },
    { city: 'San Andrés ' },
    { city: 'San Joaquín ' },
    { city: 'San Ramón ' },
    { city: 'Puerto Siles ' },
    { city: 'Magdalena ' },
    { city: 'Baures ' },
    { city: 'Huacaraje ' },
    { city: 'Cobija' },
    { city: 'Porvenir' },
    { city: 'Bolpebra' },
    { city: 'Bella Flor' },
    { city: 'Puerto Rico' },
    { city: 'San Pedro' },
    { city: 'Filadelfia' },
    { city: 'Puerto Gonzales Moreno' },
    { city: 'San Lorenzo' },
    { city: 'El Sena' },
    { city: 'Santa Rosa' },
    { city: 'Ingavi' },
    { city: 'Nueva Esperanza' },
    { city: 'Villa Nueva - Loma Alta' },
    { city: 'Santos Mercado' },
      ];
  }

  getIdCity(cityName) {
    const cities = this.getCities();
    const value = cityName.city;
    // tslint:disable-next-line: prefer-for-of
    for (let i = 0; i < cities.length; i++) {
      const city = cities[i].city;
      // console.log(i + city);
      if (city === value) {
        console.log(i + city);
        return i + 1;
      }
    }
    return 0;
  }
}
